[project]
name = "crawlingserver"
version = "0.1.0"
description = ""
authors = [
    {name = "ExitMate",email = "exitmate@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12, <3.14"
dependencies = [
    "python-dotenv (>=1.1.1,<2.0.0)",
    "motor (>=3.7.1,<4.0.0)",
    "pymongo (>=4.13.2,<5.0.0)",
    "langchain (>=0.3.27,<0.4.0)",
    "langchain-openai (>=0.3.28,<0.4.0)",
    "langchain-pinecone (>=0.2.11,<0.3.0)",
    "langchainhub (>=0.1.21,<0.2.0)",
    "black (>=25.1.0,<26.0.0)",
    "langchain-community (>=0.3.27,<0.4.0)",
    "fastapi (>=0.116.1,<0.117.0)",
    "uvicorn[standard] (>=0.35.0,<0.36.0)"
]

[tool.poetry]
packages = [
    {include = "src"}
]

[tool.poetry.scripts]
start = "src.main:production"
dev = "src.server:run_dev_server"
test-db = "src.main:dev"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
